export const IS_LOADING_CHANNEL = 'IS_LOADING_CHANNEL';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_ERR = 'FETCH_CHANNEL_ERR';
export const FETCH_CHANNEL_CONNECTION = 'FETCH_CHANNEL_CONNECTION';
export const IS_WEEKLY_ANALYTICS = 'IS_WEEKLY_ANALYTICS';
export const IS_MONTHLY_ANALYTICS = 'IS_MONTHLY_ANALYTICS';
