/**
 * Dashboard constants
 *
 */

export const SET_ACTIVE_BRAND = 'SET_ACTIVE_BRAND';
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const IS_LOADING_ACCOUNT = 'IS_LOADING_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = 'FETCH_ACCOUNT_ERROR';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_CONNECTIONS_LIST = 'SET_CONNECTIONS_LIST';
