export const FETCH_POST_SET_REQUEST = 'PUBLIC/FETCH_POST_SET_REQUEST';
export const FETCH_POST_SET_SUCCESS = 'PUBLIC/FETCH_POST_SET_SUCCESS';
export const FETCH_POST_SET_ERROR = 'PUBLIC/FETCH_POST_SET_ERROR';
