export const FETCH_PLAN = 'SIGNUP/FETCH_PLAN';
export const FETCH_PLAN_SUCCESS = 'SIGNUP/FETCH_PLAN_SUCCESS';
export const FETCH_PLAN_ERROR = 'SIGNUP/FETCH_PLAN_ERROR';
export const RESEND_ACTIVATION_EMAIL = 'SIGNUP/RESEND_ACTIVATION_EMAIL';
export const RESEND_ACTIVATION_EMAIL_SUCCESS = 'SIGNUP/RESEND_ACTIVATION_EMAIL_SUCCESS';
